eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

websiteToScrape: https://www.pionex.com/en/market/spot
debug: true
classNameOfRow: tableRow
classNameOfCell: tableBodyCell
